generation:
  max_new_tokens: 128
  do_sample: false
  temperature: 1.0
  top_p: null
  top_k: null
  repetition_penalty: 1.2

decoding_kwargs:
  cd_alpha: 1.0
  cd_beta: 0.1
  noise_step: 500

phg_kwargs:
  phg_debug: false